
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rentDB?createDatabaseIfNotExist=trueee
    username: postgres112233
    password: hrhk@113
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/patidarvjy/microservices-course-on-youtube-config-store.git
