spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/colo_role?createDatabaseIfNotExist=true
    username: postgres
    password: hrhk#
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

